import { useState } from 'react';
import { ArrowRight, Eye, EyeOff, X } from 'lucide-react';
import { signInWithEmail, signInWithGoogle, signUpWithEmail } from '../lib/supabase';

export default function CustomerAuth({ onClose, onAuthenticated }) {
  const [mode,setMode]=useState('login'),[name,setName]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[showPassword,setShowPassword]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
  const submit=async event=>{
    event.preventDefault();setLoading(true);setError('');setMessage('');
    const result=mode==='login'?await signInWithEmail(email,password):await signUpWithEmail(email,password,name);
    setLoading(false);
    if(result.error){setError(result.error.message);return}
    if(mode==='register'&&!result.data?.session){setMessage('Cuenta creada. Revisa tu correo para confirmar el acceso.');return}
    onAuthenticated();
  };
  const google=async()=>{setLoading(true);setError('');localStorage.setItem('shet-open-account-after-auth','true');const{error:googleError}=await signInWithGoogle();if(googleError){localStorage.removeItem('shet-open-account-after-auth');setError(googleError.message);setLoading(false)}};
  return <div className="customer-auth-overlay"><button className="customer-auth-backdrop" type="button" onClick={onClose} aria-label="Cerrar"/><section className="customer-auth-card"><button className="customer-auth-close" type="button" onClick={onClose} aria-label="Cerrar"><X/></button><img src="/assets/logo shet burger.png" alt="SHET BURGER"/><small>CUENTA SHET</small><h2>{mode==='login'?'Bienvenido de vuelta.':'Crea tu cuenta.'}</h2><p>{mode==='login'?'Ingresa para revisar el avance y el historial de tus pedidos.':'Tus próximos pedidos quedarán guardados en un solo lugar.'}</p><div className="customer-auth-tabs"><button className={mode==='login'?'active':''} type="button" onClick={()=>{setMode('login');setError('');setMessage('')}}>INICIAR SESIÓN</button><button className={mode==='register'?'active':''} type="button" onClick={()=>{setMode('register');setError('');setMessage('')}}>CREAR CUENTA</button></div><form onSubmit={submit}>{mode==='register'&&<label>Nombre<input required autoComplete="name" value={name} onChange={event=>setName(event.target.value)}/></label>}<label>Correo electrónico<input required type="email" autoComplete="email" value={email} onChange={event=>setEmail(event.target.value)}/></label><label>Contraseña<div className="customer-auth-password"><input required type={showPassword?'text':'password'} minLength="6" autoComplete={mode==='login'?'current-password':'new-password'} value={password} onChange={event=>setPassword(event.target.value)}/><button type="button" onClick={()=>setShowPassword(value=>!value)} aria-label={showPassword?'Ocultar contraseña':'Mostrar contraseña'}>{showPassword?<EyeOff/>:<Eye/>}</button></div></label>{error&&<div className="customer-auth-error">{error}</div>}{message&&<div className="customer-auth-message">{message}</div>}<button className="customer-auth-submit" disabled={loading}>{loading?'ESPERA…':mode==='login'?'INGRESAR':'CREAR MI CUENTA'} <ArrowRight/></button></form><div className="customer-auth-divider"><span>O CONTINÚA CON</span></div><button className="customer-auth-google" type="button" onClick={google} disabled={loading}><span className="customer-auth-google__mark">G</span> GOOGLE</button></section></div>;
}
