import { Check, Clock3, MapPin, X } from 'lucide-react';

const money = value => `$${value.toLocaleString('es-CL')}`;
const stages = ['Pedido recibido', 'En preparación', 'Listo para servir'];

export default function OrderTracker({ order, onClose }) {
  if (!order) return null;
  return <div className="tracker-overlay" role="dialog" aria-modal="true" aria-label="Estado de tu pedido"><button className="tracker-backdrop" onClick={onClose} aria-label="Cerrar seguimiento"/><aside className="tracker-panel"><header><div><small>SEGUIMIENTO · #{order.id}</small><h2>Tu pedido<br/><em>va en camino.</em></h2></div><button onClick={onClose} aria-label="Cerrar"><X/></button></header><div className="tracker-status"><div className="tracker-status__top"><span>ESTADO ACTUAL</span><b>{order.status}</b></div><div className="tracker-line">{stages.map((stage, index) => <div className={`tracker-stage${index <= order.stage ? ' is-done' : ''}${index === order.stage ? ' is-current' : ''}`} key={stage}><div>{index < order.stage ? <Check/> : index === order.stage ? <Clock3/> : <span>{index + 1}</span>}</div><p>{stage}</p></div>)}</div></div><section className="tracker-receipt"><div className="tracker-receipt__heading"><h3>Recibo del pedido</h3><span>{order.mode === 'delivery' ? 'DELIVERY' : 'RETIRO EN TIENDA'}</span></div>{order.items.map(item => <div className="tracker-item" key={item.product.id}><span>{item.quantity} × {item.product.name}</span><b>{money(item.price * item.quantity)}</b></div>)}<div className="tracker-total"><span>Total estimado</span><strong>{money(order.total)}</strong></div></section><div className="tracker-info"><MapPin/><div><b>{order.mode === 'delivery' ? 'Entrega a domicilio' : 'Retiro en tienda SHET'}</b><span>{order.mode === 'delivery' ? order.customer.address : 'Av. Principal 123, Concepción'}</span><small>{order.customer.name} · {order.customer.phone}</small></div></div><p className="tracker-note">Esta actualización es parte de la simulación del boceto.</p></aside></div>;
}
