import { useEffect, useState } from 'react';
import Header from './components/Header';import Hero from './components/Hero';import BurgerStory from './components/BurgerStory';import Campaign from './components/Campaign';import MenuSection from './components/MenuSection';import Ingredients from './components/Ingredients';import FooterCTA from './components/FooterCTA';import CartDrawer from './components/CartDrawer';import AdminPanel from './components/AdminPanel';import OrderTracker from './components/OrderTracker';import { products } from './data';import { saveOrder } from './lib/orders';
export default function App(){
 const[cart,setCart]=useState([]),[open,setOpen]=useState(false),[trackOpen,setTrackOpen]=useState(false),[orders,setOrders]=useState(()=>JSON.parse(localStorage.getItem('shet-demo-orders')||'[]')),[stock,setStock]=useState(()=>{const base=Object.fromEntries(products.map(product=>[product.id,true]));return {...base,...JSON.parse(localStorage.getItem('shet-demo-stock')||'{}')}});const latestOrder=orders[0]||null;
 useEffect(()=>{localStorage.setItem('shet-demo-orders',JSON.stringify(orders))},[orders]);useEffect(()=>{localStorage.setItem('shet-demo-stock',JSON.stringify(stock))},[stock]);
 if(window.location.pathname==='/admin')return <AdminPanel products={products} stock={stock} onToggleStock={id=>setStock(items=>({...items,[id]:!items[id]}))} orders={orders} onUpdateOrder={(id,status,stage)=>setOrders(items=>items.map(order=>order.id===id?{...order,status,stage}:order))}/>;
 const add=product=>{if(stock[product.id]===false)return;setCart(items=>{const found=items.find(item=>item.product.id===product.id);return found?items.map(item=>item.product.id===product.id?{...item,quantity:item.quantity+1}:item):[...items,{product,quantity:1}]});setOpen(true)};const change=(id,quantity)=>setCart(items=>quantity<=0?items.filter(item=>item.product.id!==id):items.map(item=>item.product.id===id?{...item,quantity}:item));
 const confirm=async details=>{const order={order_number:String(Date.now()).slice(-8),items:cart.map(item=>({product:item.product,quantity:item.quantity,price:Number(item.product.prices[0][1].replace(/\D/g,''))})),total:details.total,fulfillment:details.mode,customer_name:details.form.name,customer_phone:details.form.phone,address:details.form.address,status:'Pedido recibido',stage:0,receipt_name:details.receipt?.name||''};const result=await saveOrder(order,details.receipt);if(result.error&&result.error.message!=='Supabase no configurado')throw result.error;const localOrder={...order,id:order.order_number,mode:order.fulfillment,customer:details.form,receipt_path:result.data?.receipt_path||null};setOrders(items=>[localOrder,...items]);setCart([])};
 const count=cart.reduce((sum,item)=>sum+item.quantity,0);return <><Header cartCount={count} onCart={()=>setOpen(true)} latestOrder={latestOrder} onTrack={()=>setTrackOpen(true)}/><main><Hero onOrder={()=>setOpen(true)}/><BurgerStory/><Campaign/><MenuSection onAdd={add} stock={stock}/><Ingredients/><FooterCTA onOrder={()=>setOpen(true)}/></main>{open&&<CartDrawer cart={cart} onClose={()=>setOpen(false)} onChange={change} onClear={()=>setCart([])} onConfirm={confirm}/>} {trackOpen&&<OrderTracker order={latestOrder} onClose={()=>setTrackOpen(false)}/>}</>;
}
